# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

jobs:
  - job: Mobile
    pool:
      vmImage: 'macOS-latest'
    steps:
      - task: FlutterInstall@0
        inputs:
          channel: 'stable'
          version: 'latest'

      - task: CmdLine@2
        displayName: Upgrade & clean Flutter
        inputs:
          script: |
            $(FlutterToolPath)/flutter upgrade \
            cd ios \
            pod deintegrate \
            rm Flutter/Flutter.podspec \
            rm podfile.lock \
            $(FlutterToolPath)/flutter clean \
      
      - task: FlutterBuild@0
        displayName: "Flutter Build Apps - All platforms"
        inputs:
          target: all
          projectDirectory: '.'
          entryPoint: "lib/main.dart"
          iosCodesign: false

      - task: FlutterTest@0
        displayName: Flutter Tests
        inputs:
          projectDirectory: '.'